from .postgres_connection import postgresConnection
from .queries.total_amount_by_product_category import totalAmountByProductCategory
from .figures.total_amount_by_product_category import totalAmountByProductCategoryFig
from .queries.inventory_size_by_product_by_country import inventorySizeByProductByCountry
from .figures.inventory_size_by_product_by_country import inventorySizeByProductByCountryFig
from .queries.database_class_diagram import databaseClassDiagram
from .figures.database_class_diagram import databaseClassDiagramFig
from .queries.average_price_rate_by_country import averagePriceRateByCountry
from .figures.average_price_rate_by_country import averagePriceRateByCountryFig
from .queries.customer_count_by_country import customerCountByCountry
from .figures.customer_count_by_country import customerCountByCountryFig
from .queries.customer_registration_by_country import customerRegistrationByCountry
from .figures.customer_registration_by_country import customerRegistrationByCountryFig
from .queries.distributor_count_by_country import distributorCountByCountry
from .figures.distributor_count_by_country import distributorCountByCountryFig
from .queries.total_amount_by_year import totalAmountByYear
from .figures.total_amount_by_year import totalAmountByYearFig
from .queries.total_sales_by_country import totalSalesByCountry
from .figures.total_sales_by_country import totalSalesByCountryFig
from .queries.total_sales_by_distributor import totalSalesByDistributor
from .figures.total_sales_by_distributor import totalSalesByDistributorFig


